### PR TITLE
update to latest version of llir/llvm

### PR DESCRIPTION
**Pull request by mewmew**
Test cases passing:

```
$ ./test.bash 
-------------------------
Testing blessedvirginmary
-------------------------
 PASS branch/nestedbranch.ll
 PASS functions/paramorder.ll
 PASS math/threeminusone.ll
 PASS math/math_stuff.ll
 PASS basic/ptrtoarray.ll
 PASS basic/ret_zero.ll
 PASS math/comparison.ll
 PASS functions/playnice.ll
 PASS branch/falsebranch.ll
 PASS branch/branch.ll
 PASS basic/array.ll
 PASS functions/addone.ll
 PASS functions/noargs.ll
 PASS math/fourdivtwo.ll
 PASS functions/square.ll
 PASS basic/ptr.ll
 PASS math/twotimestwo.ll
 PASS math/oneplusone.ll
```

### CODE REVIEW

**Comment by mewmew** [comment]
Hi @NateGraff,

It was fun to discover your LLVM IR to Bash transpiler the other day. This PR updates blessedvirginmary to make use of the latest version of the llir/llvm API, and is part of the preparation for the [v0.3.0 release](https://github.com/llir/llvm/issues/29).

Happy winter wishes from Sweden :)

Robin

**Edit:** I also added a `go.mod` file to make use of Go modules for tracking versions of dependencies.

**Comment by NateGraff** [comment]
Wow! Thanks for your contribution @mewmew! I'll try to review this in the next few days when I get a free moment.

Happy winter wishes to you too!

**Comment by mewmew** [comment]
Most happy to :)

Oh, a quick tip for when you do the review (which may be obvious, but still). You can skip whitespace changes when checking the diff: https://github.com/NateGraff/blessedvirginmary/pull/2/files?utf8=%E2%9C%93&diff=split&w=1

**Comment by mewmew** [comment]
*gentle ping*

Have a great weekend Nathaniel :)

**Comment by mewmew** [comment]
Happy new year @NateGraff :)

Made a small update to make blessedvirginmary compile again against the latest version of llir/llvm. We've essentially been doing a lot of small cleanups in preparation for the v0.3 release. It is getting closer, so there should not be too many changes after this :)

Cheers,
Robin

**Comment by mewmew** [comment]
Hi @NateGraff,

Now `v0.3.0` of `llir/llvm` has been released, so I updated this PR to make bvm use the latest version.

Just like last year, I wish you a most lovely winter holidays and a great start of 2020!

Cheerful regards,
Robin

**Comment by mewmew** [comment]
Hi @NateGraff,

As this PR has been open for quite some time, I'll close it now. If you still wish to merge, just re-open.

Wish you all the best.

Cheers,
Robin

**Pull request closed without merging**
